
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System.Collections.Generic;
using System.Linq;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     02/08/2025 15:04:39 +00:00
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Rentalthingy
{
    public static class CustomerEndpoints
    {
        public static void MapCustomerEndpoints(this IEndpointRouteBuilder app)
        {
            // Get All
            app.MapGet("/customers", (List<Customer> customers) =>
            {
                return Result.Ok(customers);
            });

            // Get by ID
            app.MapGet("/customers/{{id}}", (int id, List<Customer> customers) =>
            {
                var item = customers.FirstOrDefault(x => x.Id == id);
                return item != null ? Result.Ok(item) : Result.NotFound();
            });

            // Create
            app.MapPost("/customers", (Customer customer, List<Customer> customers) =>
            {
                customers.Add(customer);
                return Result.Created($"/customers/{{customer.Id}}", customer);
            });

            // Update
            app.MapPut("/customers/{{id}}", (int id, Customer updatedCustomer, List<Customer> customers) =>
            {
                var existingItem = customers.FirstOrDefault(x => x.Id == id);
                if (existingItem == null)
                {
                    return Result.NotFound();
                }

                existingItem.CustomerId = updatedCustomer.CustomerId;
                existingItem.FirstName = updatedCustomer.FirstName;
                existingItem.LastName = updatedCustomer.LastName;
                existingItem.Email = updatedCustomer.Email;
                return Result.Ok(existingItem);
            });

            // Delete
            app.MapDelete("/customers/{{id}}", (int id, List<Customer> customers) =>
            {
                var item = customers.FirstOrDefault(x => x.Id == id);
                if (item != null)
                {
                    customers.Remove(item);
                    return Result.NoContent();
                }

                return Result.NotFound();
            });
        }

        // Example In-Memory Data Source (for testing purposes)
        public static List<Customer> GetCustomers() => new List<Customer>
        {
            
            
            
            
            
        
            };
        }

    public class Customer
    {
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
  }
}
