


using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Linq;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     02/08/2025 12:37:47 +00:00
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Generated
{
    public static class RentalEndpoints
    {
        public static void MapRentalEndpoints(this IEndpointRouteBuilder app)
        {
            // Get All
            app.MapGet("/rentals", (List<Rental> rentals) =>
            {
                return Results.Ok(rentals);
            });

            // Get by ID
            app.MapGet("/rentals/{{id}}", (int id, List<Rental> rentals) =>
            {
                var item = rentals.FirstOrDefault(x => x.Id == id);
                return item != null ? Results.Ok(item) : Results.NotFound();
            });

            // Create
            app.MapPost("/rentals", (Rental rental, List<Rental> rentals) =>
            {
                rentals.Add(rental);
                return Results.Created($"/rentals/{{rental.Id}}", rental);
            });

            // Update
            app.MapPut("/rentals/{{id}}", (int id, Rental updatedRental, List<Rental> rentals) =>
            {
                var existingItem = rentals.FirstOrDefault(x => x.Id == id);
                if (existingItem == null)
                {
                    return Results.NotFound();
                }

                existingItem.RentalId = updatedRental.RentalId;
                existingItem.RentalDate = updatedRental.RentalDate;
                existingItem.ReturnDate = updatedRental.ReturnDate;
                existingItem.RentalFee = updatedRental.RentalFee;
                existingItem.CustomerId = updatedRental.CustomerId;
                existingItem.VehicleId = updatedRental.VehicleId;
                return Results.Ok(existingItem);
            });

            // Delete
            app.MapDelete("/rentals/{{id}}", (int id, List<Rental> rentals) =>
            {
                var item = rentals.FirstOrDefault(x => x.Id == id);
                if (item != null)
                {
                    rentals.Remove(item);
                    return Results.NoContent();
                }

                return Results.NotFound();
            });
        }

        // Example In-Memory Data Source (for testing purposes)
        public static List<Rental> GetRentals() => new List<Rental>
        {
            new Rental { Id = 1, Name = "Rental 1", Price = 10.5m * 1, Stock = 100 * 1 },
            new Rental { Id = 2, Name = "Rental 2", Price = 10.5m * 2, Stock = 100 * 2 },
            new Rental { Id = 3, Name = "Rental 3", Price = 10.5m * 3, Stock = 100 * 3 },
            new Rental { Id = 4, Name = "Rental 4", Price = 10.5m * 4, Stock = 100 * 4 },
            new Rental { Id = 5, Name = "Rental 5", Price = 10.5m * 5, Stock = 100 * 5 },
        
            };
        }

    public class Rental
    {
        public int RentalId { get; set; }
        public datetime RentalDate { get; set; }
        public datetime ReturnDate { get; set; }
        public decimal RentalFee { get; set; }
        public int CustomerId { get; set; }
        public int VehicleId { get; set; }
  }
}
