


############################################
# AutoGenerated by Maker 02/08/2025 13:09:02
############################################
FROM nginx:latest
COPY Rentalthingy /etc/nginx/nginx.conf
COPY Rentalthingy /etc/nginx/conf.d/default.conf

