
/********************************************
   AutoGenerated by Maker 02/08/2025 17:04:33
********************************************/

using System;
using System.Collections.Generic;
using System.Text.Json;

namespace Rentalthingy;
            public class Rental { 
                           public int RentalId {get; set;}
                               public DateTime RentalDate {get; set;}
                               public DateTime ReturnDate {get; set;}
                               public decimal RentalFee {get; set;}
                               public int CustomerId {get; set;}
                               public int VehicleId {get; set;}
                    }
        
            public class Customer { 
                           public int CustomerId {get; set;}
                               public string FirstName {get; set;}
                               public string LastName {get; set;}
                               public string Email {get; set;}
                    }
        
            public class Vehicle { 
                           public int VehicleId {get; set;}
                               public string Make {get; set;}
                               public string Model {get; set;}
                               public int Year {get; set;}
                               public string Color {get; set;}
                               public decimal DailyRate {get; set;}
                    }
        
     